# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lug_it' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lug_it
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  
end
